### ISSUE TITLE
Update the version of all packages in pubspec yaml, and make sure project is compatible with latest version of flutter

### ISSUE THREAD

**Issue by Sam1kumar** [FieldAssist/fa_flutter_ui_kit#31]

**Comment by apgapg** [comment]
@namanpopli Can you pick this up, I guess you are managing this repo

**Comment by namanpopli** [comment]
@apgapg @Sam1kumar UI Kit is compatible with the latest version of flutter.

**Comment by apgapg** [comment]
@namanpopli report the same on discord group too
