### ISSUE TITLE
Replace deprecated widgets

### ISSUE THREAD

**Issue by Ritsz123** [FieldAssist/fa_flutter_ui_kit#63]
Replace deprecated widgets such as RaisedButton from ui kit
need to pick this up urgently before migrating to flutter 3.3

**Comment by Ritsz123** [comment]
@vatsal201 Close this issue when code gets merged

**Comment by Ritsz123** [comment]
@vatsal201 Close this issue when code gets merged

**Comment by vatsal201** [comment]
Merged by @TusharFA
